server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

    charset utf-8;

    # Reescrever todas as requisições para o Front Controller (public/index.php)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Desativar logs para favicon e robots.txt
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Passar scripts PHP para o serviço FPM (aula_php8.5)
    location ~ \.php$ {
        fastcgi_pass aula_php8.5:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    # Bloquear acesso a arquivos ocultos (.htaccess, .env, etc)
    location ~ /\. {
        deny all;
    }
}
